import Head from "next/head";
import { Button, FormGroup, GridCol, GridContainer, GridRow, TextField } from "@taikai/rocket-kit";
import { Container, Main, NavBar, BrandName, Menu, Footer, SubTitle, Content, Test, Title1 } from "../styles/home";
import React, { FormEvent, useEffect, useState } from 'react';

// import { deploy_multisig } from  "../../contract/scripts/deploy_multisig"

export default function Admin() {

    

    const createMuliSigContract = async (event: FormEvent) => {
        event.preventDefault()
        const form = event.target as HTMLFormElement
    
        const owners = [
            form.wallet_1.value as string,
            form.wallet_2.value as string,
            form.wallet_3.value as string,
        ]

        let contract_address = await deploy_multisig(owners, 3)

        console.log(contract_address)
    
    }
  


  return (
    <Container>
      <Head>
        <title>Web3 BoilerPlate by Lay3rX</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Content>
          <Title1>Create a MultiSig Contract</Title1>

          <form onSubmit={createMuliSigContract}>

            <GridContainer>
              <GridRow className="pt-5 pb-5">
                
              <GridCol>
                  <FormGroup label="address">
                    <TextField 
                      name="wallet_1"
                      placeholder="Wallet of the owner n°1"
                    />
                  </FormGroup>
                </GridCol>
            </GridRow>
            <GridRow>
                <GridCol>
                  <FormGroup label="address">
                    <TextField 
                      name="wallet_2"
                      placeholder="Wallet of the owner n°2"
                    />
                  </FormGroup>
                </GridCol>
            </GridRow>
            <GridRow>
                <GridCol>
                  <FormGroup label="address">
                    <TextField 
                      name="wallet_3"
                      placeholder="Wallet of the owner n°3"
                    />
                  </FormGroup>
                </GridCol>    
            </GridRow>
            

        </GridContainer>

            <Button
              ariaLabel="Connect"
              className="pt-5"
              color="green"
              value="Create new property"
              variant="solid"
            />

          </form>

        </Content>
      </Main>
    </Container>
  );
}
