import Head from "next/head";
import { Button } from "@taikai/rocket-kit";
import { useWeb3 } from "../hooks/useWeb3";
import { Container, Main, NavBar, BrandName, Menu , Footer, SubTitle, Content, Test, Title1}  from "../styles/home";
import ConnectModal from "../components/connect-wallet-modal";
import React, { useEffect, useState } from 'react';
import ClickableEthAddress  from "../components/clickable-eth-address";
import { ERC1155Standard, ERC721Collectibles, Web3Connection } from "@taikai/dappkit";

import { ERC1155Ownable } from '@taikai/dappkit';

export default function About() {


  async function nftCollection() {

    let MULTISIG_CONTRACT = "0xc5EF893518208119968B294eE95d341C48c0f2e0";

    const web3Connection = new Web3Connection({ 
        web3Host: 'http://127.0.0.1:7545'
    });
    
    await web3Connection.start();
    await web3Connection.connect();
    const deployer = new ERC1155Standard(web3Connection);
    
    await deployer.loadAbi();
    const tx = await deployer.deployJsonAbi("https://api.npoint.io/47687dcd634e96f824e3");

    /* Instantiate and use your new ERC1155 Token Contract*/
    const erc1155Contract = new ERC1155Standard(web3Connection, tx.contractAddress);
    await erc1155Contract.start();
    
    erc1155Contract.mint(MULTISIG_CONTRACT, 0, 1000, '0x00');
    console.log(erc1155Contract);

  }


  async function deployERC1155() {
    
    const web3Connection = new Web3Connection({ 
      web3Host: 'http://127.0.0.1:7545'
    });

    await web3Connection.start();
    await web3Connection.connect(); 

    /* Create an ERC1155Ownable Deployer */
    const deployer = new ERC1155Ownable(web3Connection);

    /* Deploy the ERC1155 Contract */
    await deployer.loadAbi();
    const tx = await deployer.deployJsonAbi("https://api.npoint.io/47687dcd634e96f824e3");
    
    /* Instantiate and use your new ERC1155 Token Contract*/
    const erc1155Contract = new ERC1155Ownable(web3Connection, tx.contractAddress);
    await erc1155Contract.start();

    erc1155Contract.mint('0xTO_ADDRESS', 0, 1000, '0x12345678');






  }



  // async function collectionNFT() {

  //   const web3Connection = new Web3Connection({ 
  //     web3Host: 'http://127.0.0.1:7545'
  //   });
    
  //   await web3Connection.start();
  //   await web3Connection.connect();
    


  //   const erc721Collectibles = new ERC721Collectibles(web3Connection);
    
  //   await erc721Collectibles.loadAbi();
    
  //   // Deploy
  //   const transactionReceipt = await erc721Collectibles.deployJsonAbi(
  //       "Art | BEPRO",
  //       "B.E.P.R.O",
  //       1000,
  //       "0xc5EF893518208119968B294eE95d341C48c0f2e0",
  //       "0xc5EF893518208119968B294eE95d341C48c0f2e0",
  //       "0x00",
  //       "0xc5EF893518208119968B294eE95d341C48c0f2e0" 
  //    );

  //   //     "0xDAI_ADDRESS",
  //   //     "0xPURCHASE_TOKEN",
  //   //     "0xBASE_FEE_ADDRESS",
  //   //     "0xOTHER_ADDRESS" 
    
  //   console.log(transactionReceipt);

  // }


  const { connected } = useWeb3();
  const [isConnectModal, setConnectModal] = useState(false);

  return (
    <Container>
      <Head>
        <title>Web3 BoilerPlate by Lay3rX</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Content>
          <Title1>Create a new building</Title1>
            

          <Button
              ariaLabel="Connect"
              className="button"
              color="green"
              value="Connect"
              variant="solid"
              action={() => nftCollection()}
            />

        </Content>        
      </Main>
      <Test>test</Test>
      <Footer>Made with ❤️ by <strong>LayerX</strong> - 2023</Footer>
    </Container>
  );
}
