import Head from "next/head";
import { Button } from "@taikai/rocket-kit";
import { useWeb3 } from "../hooks/useWeb3";
import { Container, Main, NavBar, BrandName, Menu , Footer, Title1, Title2, Title4, SubTitle, Content, Banner, Section}  from "../styles/home";
import ConnectModal from "../components/connect-wallet-modal";
import React, { useEffect, useState } from 'react';
import ClickableEthAddress  from "../components/clickable-eth-address";
import Link from 'next/link';
import Image from 'next/image';

export default function Home() {

  const { connected } = useWeb3();
  const [isConnectModal, setConnectModal] = useState(false);
  const [scroll, setScroll] = useState(false);

  useEffect(() => {
    console.log('test');
    
    window.addEventListener("scroll", () => {
      console.log('test');
      setScroll(window.scrollY > 50);
    });
  }, []);

  return (
    <Container>
      <Head>
        <title>Web3 BoilerPlate by Lay3rX</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar className={`g-nav fixed flex justify-between w-full px-10 py-3 z-20 backdrop-blur-md ${scroll ? 'has-scrolled' : ''}`}>
        <BrandName>Higuerón South Residences</BrandName>
        <Menu>
          {!connected && (
            <Button
              ariaLabel="Connect"
              className="button"
              color="green"
              value="Connect"
              variant="solid"
              action={()=> setConnectModal(true)}
            />
          )}
          {connected && <ClickableEthAddress onClick={()=> setConnectModal(true)}/>}
        </Menu>
      </NavBar>
      {isConnectModal && <ConnectModal onClose={()=> setConnectModal(false)}/>}
      <Main>
        <Content className="">
          <Banner className="header-main grid grid-cols-12">
            <figure className="col-span-6">
              <iframe title="Youtube video player" src="//www.youtube.com/embed/1u851eyXhBM?autoplay=1&amp;loop=1&amp;playlist=1u851eyXhBM&amp;controls=0&amp;mute=1&amp;iv_load_policy=3&amp;disablekb=1&amp;wmode=transparent&amp;showinfo=0" allowfullscreen="true"  width="100%" height="100%"></iframe>
            </figure>
            <div className="col-span-4 col-start-8 flex flex-col justify-center text-center">
              <Title1>A new world, feel it</Title1>
              <Title2>A NEW WAY OF LIVING LIFE</Title2>
            </div>
          </Banner>

          <Section className="s-who grid grid-cols-12">
            <div className="col-span-4">
              <Title2>Tipologías</Title2>

              <p>El diseño de South Residences está inspirado en Higuerón Hotel ya que sigue la misma línea vanguardista y utiliza materiales sostenibles como el acero cortén, la piedra y la madera.</p>
              <p>Las viviendas estarán numeradas como si de un hotel se tratase y esto no es casualidad. Las personas que compren una vivienda en South Residences podrán disfrutar de servicios exclusivos de la mano de Higuerón Hotel Curio Collection by Hilton 5*.</p>
              <p>El arte es un pilar fundamental de este proyecto. Los propietarios vivirán rodeados de piezas exclusivas como si de una galería se tratase. Además, los 4 bloques toman el nombre de artistas contemporáneos reconocidos como Leiro, Brinkmann, Darko y Alfil.</p>
            </div>
            <div className="col-span-3 col-start-8 flex flex-col justify-center text-center">
              <Image src="/sitting-1.svg" alt="me" width="100" height="100" />
            </div>
          </Section>

          
          <Link href="/about">About Us</Link>
        </Content>        
      </Main>
      <Footer>Made with ❤️ by <strong>our team</strong> - 2023</Footer>
    </Container>
  );
}
